member:
 rent:
  min: 7
  max: 30
 price:
  discount: 3
vehicle:
 default:
  model: cross over
duration: all
my.greeting=Hello world
my.list.values=One,Two,Three

dbProperties={connectionString: 'http:/localhost:8080', userName: 'root'}
